### ISSUE TITLE
unix 01 notes redirect stdout and error to file

### ISSUE THREAD

**Issue by srobb1** [prog4biol/pfb2018#10]
change 

|||
|-|--|
| > myfile.txt 2>&1 | Redirect both stdout and stderr to file | 

to 

|||
|-|--|
| &> myfile.txt  | Redirect both stdout and stderr to file |

**Comment by procho** [comment]
I think this change messed things up.
We changed to bash so the 2>&1 is correct.

&> is a tcsh syntax

**Comment by srobb1** [comment]
`&>` does work in bash
use this test
```perl
#!/usr/bin/perl
use strict;
use warnings;

print "this stdout\n";
warn "this is stderr\n";
```

```
(base) mp181vbhv2j:scripts smr$ perl perl_Test.pl
this stdout
this is stderr
(base) mp181vbhv2j:scripts smr$ perl perl_Test.pl 1>out  2>err
(base) mp181vbhv2j:scripts smr$ cat out
this stdout
(base) mp181vbhv2j:scripts smr$ cat err
this is stderr
(base) mp181vbhv2j:scripts smr$ perl perl_Test.pl &> allout
(base) mp181vbhv2j:scripts smr$ cat allout
this is stderr
this stdout
```

made changes 
https://github.com/prog4biol/pfb2019/commit/590eb08f5879eeb676b6f499532e54ea0ed11a81
