### ISSUE TITLE
GIT IS HARD

### ISSUE THREAD

**Issue by webbshasta** [prog4biol/pfb2018#14]
We need to include in the notes and lecture:

1) how to delete from the remote AND local (git rm, commit push)
2) how to recover files that are still in your remote to re-add them to your local repo (git checkout? git reset HEAD?)
3) how to fully sync remote and local when files are deleted locally (git add -u, commit, push)

**Comment by srobb1** [comment]
https://github.com/prog4biol/pfb2019/commit/03cb77c9fd3908e1146e1368a232c17c8acaa73a
https://github.com/prog4biol/pfb2019/commit/085282a3b002ecaa15276e22d202bf1e071ee70c

i dont have anything about detached heads.  maybe i should add something... i dont know
