### ISSUE TITLE
feedback about text editors

### ISSUE THREAD

**Issue by webbshasta** [prog4biol/pfb2018#31]
Might be a good idea to introduce text editors in unix 2. some students felt it was a waste of time to learn nano and then have to learn vi or emacs the next day. they also said it would be useful to have a more structured intro to each of them (perhaps a task list of stuff to do?). I would advocate for a 15-min per text editor workshop on night 1, to get people into the habit of using one. with the most basic commands in vi and emacs, its really not that much harder that nano and saves us time on day two.

**Comment by srobb1** [comment]
Need to label this section as a lecture and have a problem set

For each editor:
1. open and create a new file
2. write a 10 lines of text or code
3. delete a line
4. insert a new line at line 2 
5. Copy line 5
6. Paste this line above line 1
7. Cut line 3 and paste below line 6 
8. Go to line 4
9. Save and exit

**Comment by srobb1** [comment]
removed nano, added vi. emacs can be covered in a review session.

https://github.com/prog4biol/pfb2019/commit/adc9cf48df1f1b30f13bfd0eb03cf6284247f662
