### ISSUE TITLE
on problemset 5 change #11

### ISSUE THREAD

**Issue by webbshasta** [prog4biol/pfb2018#42]
We should ask them to 

1) make a set with `set()` 
2) make a set with mySet = {}

ex) 

>>> mySet = set('ATGTGGG')
>>> mySet2 = {'ATGCCT'}

**Comment by srobb1** [comment]
done
https://github.com/prog4biol/pfb2019/commit/b644978fb68a0d0e5bff33fc1ba410dabe3363fa
