### ISSUE TITLE
nested dictionary loop example

### ISSUE THREAD

**Issue by nomascus** [prog4biol/pfb2018#54]
Can we add a script example to Python 8 that shows how to build a dictionary of dictionaries with loops? Perhaps something from a multifasta file? This seems like a more likely example of what people will be doing in the real world, but we haven't really shown how to build nested structures with loops. This sort of example was in the perl lectures, no?

**Comment by srobb1** [comment]
done. use loop to build nt_count dict in dict lecture (python 5).
https://github.com/prog4biol/pfb2019/commit/1b8fe792a09f312db05f769d102c59b1496aea1c
