### ISSUE TITLE
consider splitting multi-dimensional data structures lecture and exceptions lecture

### ISSUE THREAD

**Issue by webbshasta** [prog4biol/pfb2018#55]
Not sure where there is space to put this, but i think pairing multi-dim data structures and exceptions is a ton for one lecture. students were getting visibly distracted during the exceptions part. either more breaks, cut exceptions to shorter length, or push it to a review session?

**Comment by webbshasta** [comment]
Also, we should include an example of building a dict with a for loop.

**Comment by srobb1** [comment]
added build dict with loop  https://github.com/prog4biol/pfb2019/commit/1b8fe792a09f312db05f769d102c59b1496aea1c

made exceptions its own section. will break inbetween dat.struc and exceptions https://github.com/prog4biol/pfb2019/commit/c79d94b6e3b5097c7618cd357e17b249bb30ba73
