### ISSUE TITLE
Python Identifiers

### ISSUE THREAD

**Issue by bredeson** [prog4biol/pfb2018#7]
Stricly speaking, "token" or "variable name" would probably be a better word choice to replace "identifier". When students start googling about "identifiers" they are unlikely to find search hits that will reflect what they are intending to search for.

Token is the old-school/CS-y way of referring a variable, function, etc name. Everything in Python is an object reference, and therefore a variable, so "variable name" would be a natural choice and less confusing.

**Comment by srobb1** [comment]
fixed it https://github.com/prog4biol/pfb2018/commit/5685934fdd7ead883e93211c3c5fb2804851b246

**Comment by procho** [comment]
Yes, this is a nice clarification Jessen!
Thank you
